[package]
name = "runkitd"
version = "0.1.0"
edition = "2024"

[dependencies]
runkit-core = { path = "../runkit-core" }
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
